// GetGBIX.cpp : Defines the entry point for the console application.
//

#include "stdafx.h"

int main(int argc, char* argv[])
{
	FILE *fIn, *fOut;
	char buffer[512], *b;
	unsigned long GBIX;

	if (argc != 2) {
		fprintf (stderr, "Usage: GetGBIX <filename>\n");
		exit(1);
	}

	fIn = fopen (argv[1], "rb");
	if (fIn == NULL) {
		fprintf (stderr, "Unable to open input file '%s'\n\r", argv[1]);
		exit (1);
	}

	strcpy (buffer, argv[1]);
	b = strchr (buffer, '.');
	if (b == NULL) {
		fprintf (stderr, "Unable to parse input filename '%s'\nr", argv[1]);
		exit(1);
	}
	strcpy (b, ".h");

	fOut = fopen (buffer, "w");
	if (fOut == NULL) {
		fprintf (stderr, "Unable to open output file '%s'\n\r", buffer);
		exit(1);
	}

	// Find the GBIX
	do {
		fread (&GBIX, 4, 1, fIn);
		if (GBIX == *(unsigned int *)&"GBIX")
			break;
	} while (!feof (fIn));
	if (feof (fIn)) {
		fprintf (stderr, "Unable to find GBIX in file '%s'\n\r", argv[1]);
		exit(1);
	}
	fread (&GBIX, 4, 1, fIn);
	assert (GBIX == 4 || GBIX == 8);
	fread (&GBIX, 4, 1, fIn);
	fclose (fIn);

	fprintf (fOut, "0x%x // Automatically generated by GetGBIX - do not edit by hand\n", GBIX);
	fclose (fOut);

	return 0;
}
