ENTRY 5
	SCRIPT CAN BE SKIPPED
	INTELLIGENCE OFFICER
		TIME 90
		START
			TEXT RD ADVANCED TRAINING FACILITY, NEVADA
			TEXT 12:04
			TEXT ADVANCED COMBAT TRAINING 1
			TEXT YOU HAVE 3 MINUTES TO KILL 160 FOOTSOLDIERS. 
		END
