//scenes start here

ENTRY 0
	SCRIPT STOPS THE GAME
	SCRIPT CAN BE SKIPPED
	INTELLIGENCE OFFICER
		TIME 90
		START
			TEXT `VOL_LOCATION
			TEXT `VOL_TIME
			TEXT `VOL_OBJECTIVE
			TEXT `VOL_BRIEFING
		END

