// --------------------------------------------------------------------------------------------------------
//	GenericSFX.h
//
// This header file was auto-generated by the Sega mkbank utility.
// Do not modify this file by hand.
//
// Rev:	10/20/1999 3:39 pm - File Generated
// --------------------------------------------------------------------------------------------------------

#ifndef	_GENERICSFX_H
#define	_GENERICSFX_H


#define		GENERICSFX_FILENAME		"GenericSFX.kat"
#define		GENERICSFX_BANK_DATA_SIZE		249064
#define		GENERICSFX_BANK_HEADER_SIZE		752
#define		GENERICSFX_RD_AFTERBURNER_LP_WAV			0
#define		GENERICSFX_RD-DEEPM_WAV			1
#define		GENERICSFX_STEADTENG12_WAV			2
#define		GENERICSFX_JETLOOP5M_WAV			3
#define		GENERICSFX_SHIELD_WAV			4
#define		GENERICSFX_RD_WEAPON_MISSILE_1_WAV			5
#define		GENERICSFX_EX_LARGE_BLAST1_WAV			6
#define		GENERICSFX_EX_MEDIUM_BLAST1_WAV			7
#define		GENERICSFX_EX_TNT_EXPLOSION_WAV			8
#define		GENERICSFX_HITMETAL2_M_WAV			9
#define		GENERICSFX_LOCK_ON_WAV			10
#define		GENERICSFX_RD_RUGER39_WAV			11
#define		GENERICSFX_NA_WAV			12
#define		GENERICSFX_SELECT_WAV			13
#define		GENERICSFX_START_WAV			14
#define		GENERICSFX_RVBQSND_FOB			15
#define		GENERICSFX_RVBQSND_FPB			16


#endif	//	end of _GENERICSFX_H
