//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by RDEdit.rc
//
#define IDS_LIBDESCRIPTION              1
#define IDS_CATEGORY                    2
#define IDS_CLASS_NAME                  3
#define IDOK2                           3
#define IDS_PARAMS                      4
#define IDCANCEL2                       4
#define IDS_OBJECT_CLASS_NAME           5
#define IDS_OBJECT_CATEGORY             6
#define IDS_RB_PARAMETERS               7
#define IDS_RB_CREATIONMETHOD           8
#define IDS_OBJECT_NAME                 9
#define IDS_RB_HAS_STRAT                10
#define IDS_OBJEXP_CLASS_NAME           11
#define IDS_HELPER_CLASS_NAME           12
#define IDS_STRAT_CLASS                 12
#define IDS_HELPER_CATEGORY             13
#define IDS_HELPER_NAME                 14
#define IDS_RB_DISPLAY                  15
#define IDS_PREVIEW_CATEGORY            16
#define IDS_PREVIEW_CLASS_NAME          17
#define IDS_COLLISION_CLASS_NAME        18
#define IDS_COLLISION_CATEGORY          19
#define IDS_OBJFLAGS                    20
#define IDS_LEVELFLAGS                  20
#define IDS_OBJ_FLAGS_CLASS_NAME        21
#define IDS_COM_CLASS_NAME              22
#define IDS_COM_CAT                     23
#define IDS_AVCU_CNAME                  24
#define IDS_AVCU_PANELTITLE             25
#define IDS_AVCM_CNAME                  26
#define IDS_AVCM_ONAME                  27
#define IDS_AVCM_PANELTITLE             28
#define IDS_AVCU_PROGRESS               29
#define IDS_LIBDESCRIPTION2             30
#define IDS_LEVEL_FLAGS_CLASS_NAME      31
#define IDS_MATERIAL                    32
#define IDS_BASIC                       33
#define IDS_TEXTURE                     34
#define IDS_PASTED                      35
#define IDS_TEXPROP                     36
#define IDS_NONE                        37
#define IDS_VIS_CLASS_NAME              38
#define IDS_VIS_CAT                     39
#define IDS_CAMCONTROLS                 40
#define IDS_ANIMCONTROL                 41
#define IDS_CONV                        42
#define IDS_SUBMAT                      43
#define IDS_SHADBOX                     44
#define IDS_SHADBOX_CREATIONMETHOD      45
#define IDS_SHADBOX_KEYBOARDENTRY       46
#define IDS_SHADBOX_PARMS               47
#define IDS_SB_LENGTH                   48
#define IDS_SB_WIDTH                    49
#define IDS_SB_HEIGHT                   50
#define IDS_CAMPPOINT                   51
#define IDS_SPLINEMOD                   52
#define IDD_PANEL                       101
#define IDD_HELPERPARAM                 102
#define IDD_VCMOD_PANEL                 102
#define IDD_BOXPARAM2                   103
#define IDD_CHOOSE_OBJECT               105
#define IDD_EXPORTER                    108
#define IDD_PREVIEW                     109
#define IDD_COLLISION                   110
#define IDB_IMAGELIST                   111
#define IDD_OBJFLAGS                    111
#define IDD_COM                         112
#define IDD_DIALOG1                     113
#define IDD_VCUTIL_PANEL                114
#define IDD_LEVELFLAGS                  115
#define IDD_STRATLIST                   116
#define IDD_CAMCONTROLS                 118
#define IDD_ANIMCONTROL                 119
#define IDD_CAMPPOINT                   121
#define IDD_SPLINEMOD                   122
#define IDD_BOXPARAM1                   145
#define IDC_SH_EDIT                     216
#define IDC_SS_EDIT                     217
#define IDC_OP_EDIT                     218
#define IDC_SS_EDIT2                    219
#define IDC_SH_SPIN                     328
#define IDC_SS_SPIN                     329
#define IDC_OP_SPIN                     330
#define IDC_CLOSEBUTTON                 1000
#define IDC_DOSTUFF                     1000
#define IDC_ID                          1000
#define IDC_RADIUS                      1001
#define IDC_VCUTIL_APPLY                1001
#define IDC_OBJECT_HAS_STRAT            1002
#define IDC_SPIN_TCBSPIN                1002
#define IDC_MASS                        1002
#define IDC_SPIN_TCBEDIT                1003
#define IDC_MOI                         1003
#define IDC_VCUTIL_DIFFUSE              1003
#define IDC_UID                         1004
#define IDC_VCUTIL_SCENELIGHTS          1004
#define IDC_ABLUE                       1004
#define IDC_OBJECT_TYPE                 1005
#define IDC_IDSPINNER                   1005
#define IDC_VCUTIL_UPDATEALL            1005
#define IDC_RADIUSSPINNER               1006
#define IDC_STRAT_OBJECTS               1006
#define IDC_FBLUE                       1006
#define IDC_OBJECT_TREE                 1007
#define IDC_MASSSPINNER                 1007
#define IDC_PATHPICK1                   1007
#define IDC_BOX                         1008
#define IDC_MOISPINNER                  1008
#define IDC_ABLUESPINNER                1008
#define IDC_LENSPINNER                  1008
#define IDC_dCROSS                      1009
#define IDC_UIDSPINNER                  1009
#define IDC_DISPLAY_ARROW               1009
#define IDC_FOGNEARSPINNER              1009
#define IDC_MESH                        1010
#define IDC_OBJECTNAME                  1010
#define IDC_HEIGHTEDIT                  1010
#define IDC_REFACE                      1011
#define IDC_FRICTION_X                  1011
#define IDC_FRIENDLY                    1011
#define IDC_FOGFARSPINNER               1011
#define IDC_WIDTHSPINNER                1011
#define IDC_FRICTION_X_SPINNER          1012
#define IDC_ENEMY                       1012
#define IDC_SCAPEINTENSITYSPINNER       1012
#define IDC_LIGHTEDIT                   1012
#define IDC_FRICTION_Y                  1013
#define IDC_FRIENDLY2                   1013
#define IDC_STRATINTENSITYSPINNER       1013
#define IDC_INTPARAMSPINNER             1013
#define IDC_PRIEDIT                     1013
#define IDC_FRICTION_Y_SPINNER          1014
#define IDC_FRIENDLY3                   1014
#define IDC_FBLUESPINNER                1014
#define IDC_FLOATPARAMSPINNER           1014
#define IDC_FRICTION_Z                  1015
#define IDC_FRIENDLY4                   1015
#define IDC_FOVSPINNER                  1015
#define IDC_PARENT                      1015
#define IDC_FRICTION_Z_SPINNER          1016
#define IDC_FRIENDLY5                   1016
#define IDC_FARZSPINNER                 1016
#define IDC_PATHPICK4                   1017
#define IDC_EXPROT                      1017
#define IDC_TRIGPOINT1                  1017
#define IDC_HEIGHTSPINNER               1017
#define IDC_USEMAP_DI                   1017
#define IDC_EXPROTSPINNER               1018
#define IDC_ACTTRIGPOINT                1018
#define IDC_DISTSPINNER                 1018
#define IDC_LIGHTSPIN                   1018
#define IDC_FRICTION_X2                 1019
#define IDC_ACTNUM                      1019
#define IDC_LOOKHEIGHTSPINNER           1019
#define IDC_PRISPIN                     1019
#define IDC_TRI_COUNT                   1020
#define IDC_FRICTION_X_SPINNER2         1020
#define IDC_IPARAM                      1020
#define IDC_QUAD_COUNT                  1021
#define IDC_FRICTION_Y2                 1021
#define IDC_IPARAMNUM                   1021
#define IDC_FRICTION_Y_SPINNER2         1022
#define IDC_FPARAM                      1022
#define IDC_FRICTION_Z2                 1023
#define IDC_FPARAMNUM                   1023
#define IDC_FRICTION_Z_SPINNER2         1024
#define IDC_EVENTPOINT                  1024
#define IDC_DELETIONEVENTPOINT          1025
#define IDC_IGNPARENT                   1026
#define IDC_PREVIEW                     1028
#define IDC_CONVERT                     1029
#define IDC_CONVERTMAT                  1030
#define IDC_FORCECALC                   1031
#define IDD_MATERIAL                    1031
#define IDC_STATS                       1031
#define IDC_CALC_MATRIX                 1032
#define IDC_MAP_CONVERT                 1032
#define IDC_SAVESCAPE                   1032
#define IDD_VISBOX                      1032
#define IDC_TARGETABLE                  1033
#define IDD_TEXTURES                    1033
#define IDC_SAVEMAP                     1033
#define IDC_HIGH_D_COLL                 1034
#define IDC_SAVEBOTH                    1034
#define IDC_CALCULATE                   1035
#define IDC_LEVELNAME                   1035
#define IDC_SAVESOLEMAP                 1036
#define IDC_VIEWSTRATS                  1037
#define IDC_AUTORUN_GDS                 1038
#define IDC_AUTORUN_CODE                1039
#define IDC_NORMPATH                    1040
#define IDC_CONVNAMES                   1040
#define IDC_OFFPATH                     1041
#define IDC_DELETESTRATS                1041
#define IDC_NORMPATH2                   1042
#define IDC_INSTANCE                    1042
#define IDC_PLANEMOVE                   1042
#define IDC_FREEZESTRATS                1042
#define IDC_NORMPATH3                   1043
#define IDC_HOVERMOVE                   1043
#define IDC_EDITOR                      1043
#define IDC_GRAVITYONC                  1044
#define IDC_SAVEOBJ                     1044
#define IDC_CALCRELVELC                 1045
#define IDC_EDIT1                       1045
#define IDC_COLLSTRATC                  1046
#define IDC_EDIT2                       1046
#define IDC_COLLFLOORC                  1047
#define IDC_EDIT3                       1047
#define IDC_ENTIRENET                   1048
#define IDC_EDIT4                       1048
#define IDC_OWNROT                      1049
#define IDC_FILTER                      1049
#define IDC_CLEARWAY                    1050
#define IDC_GODMODE                     1050
#define IDC_CLEARCREATE                 1051
#define IDC_SALARY                      1051
#define IDC_CLEARACT                    1052
#define IDC_BONUS                       1052
#define IDC_ARMOUR                      1053
#define IDC_BONUS_AMT                   1053
#define IDC_HEALTH                      1054
#define IDC_CTRL_CAMERA                 1054
#define IDC_ARMOURSPINNER               1055
#define IDC_EDIT5                       1055
#define IDC_HEALTHSPINNER               1056
#define IDC_NONDELETEDSTRATS            1056
#define IDC_AGGRESSIVE                  1057
#define IDC_DEFENSIVE                   1058
#define IDC_HOLDING                     1059
#define IDC_PATH                        1060
#define IDC_IINTDEF                     1061
#define IDC_NODE                        1062
#define IDC_NODESPINNER                 1063
#define IDC_ROUTENUM                    1064
#define IDC_ROUTESPINNER                1065
#define IDC_DELAY                       1066
#define IDC_GINSU                       1066
#define IDC_ARED                        1067
#define IDC_DELAYSPINNER                1067
#define IDC_AGREEN                      1068
#define IDC_IFLOATDEF                   1068
#define IDC_AREDSPINNER                 1069
#define IDC_CLEAREVENT                  1069
#define IDC_AGREENSPINNER               1070
#define IDC_CLEARPARENT                 1070
#define IDC_FOGNEAR                     1071
#define IDC_MAP_DI                      1071
#define IDC_CLEARMODEL                  1071
#define IDC_FOGFAR                      1072
#define IDC_MAP_SP                      1072
#define IDC_MAP_PA                      1072
#define IDC_ARMOUR2                     1072
#define IDC_SCAPEINTENSITY              1073
#define IDC_AMT_DI                      1073
#define IDC_CONV                        1073
#define IDC_HEALTH2                     1073
#define IDC_STRATINTENSITY              1074
#define IDC_INTPARAM                    1074
#define IDC_AMT_SP                      1074
#define IDC_AMT_PA                      1074
#define IDC_FRED                        1075
#define IDC_FLOATPARAM                  1075
#define IDC_TWOSIDED                    1075
#define IDC_FREDSPINNER                 1076
#define IDC_COLLISION                   1076
#define IDC_OFFPATH2                    1076
#define IDC_FGREEN                      1077
#define IDC_MATCAM                      1077
#define IDC_ARMOUR3                     1077
#define IDC_FGREENSPINNER               1078
#define IDC_CAMCLEAR                    1078
#define IDC_HEALTH3                     1078
#define IDC_FOV                         1079
#define IDC_ANISOTROPIC                 1079
#define IDC_OFFPATH3                    1079
#define IDC_FARZ                        1080
#define IDC_UNLIT                       1080
#define IDC_ARMOUR4                     1080
#define IDC_HEIGHT                      1081
#define IDC_TRANSPARENT                 1081
#define IDC_CLAMP                       1081
#define IDC_AMT_ADJUST                  1081
#define IDC_HEALTH4                     1081
#define IDC_DIST                        1082
#define IDC_ADDITIVE                    1082
#define IDC_OFFPATH4                    1082
#define IDC_LOOKHEIGHT                  1083
#define IDC_SUBTRACTIVE                 1083
#define IDC_ARMOUR5                     1083
#define IDC_AAMOUNT                     1084
#define IDC_PAL_ADJUST                  1084
#define IDC_HEALTH5                     1084
#define IDC_USEMAP_PA                   1085
#define IDC_NOFILT                      1085
#define IDC_AAMOUNTSPINNER              1085
#define IDC_CLEARDELETIONEVENT          1085
#define IDC_SPIN_DI                     1086
#define IDC_BILINEAR                    1086
#define IDC_ASPEED                      1086
#define IDC_OWNPOS                      1086
#define IDC_SPIN_SP                     1087
#define IDC_TRILINEAR                   1087
#define IDC_ASPEEDSPINNER               1087
#define IDC_SPIN_PA                     1090
#define IDC_SPIN_ADJUST                 1091
#define IDC_SPIN_PAL                    1092
#define IDC_EMAP                        1093
#define IDC_PUNCHTHRU                   1094
#define IDC_SURFACE                     1095
#define IDC_BUMPMAP                     1096
#define IDC_CLEARDOME                   1097
#define IDC_CAMERACOLLISION             1097
#define IDC_INCLUSIVE                   1098
#define IDC_ENEMYCOLLISION              1098
#define IDC_EXCLUSIVE                   1099
#define IDC_BULLETCOLLISION             1099
#define IDC_VISBOX_ID                   1100
#define IDC_PLAYERCOLLISION             1100
#define IDC_VISBOX_SPIN                 1101
#define IDC_CHECK1                      1102
#define IDC_CHECK2                      1103
#define IDC_CHECK3                      1104
#define IDC_CHECK4                      1105
#define IDC_CHECK5                      1106
#define IDC_CHECK6                      1107
#define IDC_CHECK7                      1108
#define IDC_DIFFUSE                     1109
#define IDC_CHECK8                      1109
#define IDC_SPECULAR                    1110
#define IDC_CHECK34                     1110
#define IDC_CHECK17                     1111
#define IDC_CHECK18                     1112
#define IDC_RADIUS_SPIN                 1113
#define IDC_CHECK19                     1113
#define IDC_AKEY                        1114
#define IDC_CHECK20                     1114
#define IDC_AKEYSPINNER                 1115
#define IDC_CHECK21                     1115
#define IDC_ANIMNUM                     1116
#define IDC_CHECK22                     1116
#define IDC_ANIMNAME                    1117
#define IDC_CHECK23                     1117
#define IDC_RESETANIMS                  1118
#define IDC_CHECK24                     1118
#define IDC_INTERPOLATE                 1119
#define IDC_CHECK25                     1119
#define IDC_AENDKEY                     1120
#define IDC_AENDKEYSPINNER              1121
#define IDC_CASTSHADOW                  1122
#define IDC_OBJIDCREATE                 1122
#define IDC_ROUNDSHADOW                 1123
#define IDC_NEXTANIM                    1123
#define IDC_FACEON                      1124
#define IDC_PREVANIM                    1124
#define IDC_STRATMOVE                   1125
#define IDC_WATEREFFECT                 1126
#define IDC_LAVAEFFECT                  1127
#define IDC_CAMPPARENT                  1128
#define IDC_CAMPRADIUS                  1129
#define IDC_CAMPRADIUS_SPIN             1130
#define IDC_SPLINEMODPARENT             1131
#define IDC_SPLINEMODRADIUS             1132
#define IDC_SPLINEMODRADIUS_SPIN        1133
#define IDC_WRAPFIX                     1136
#define IDC_WRAP_U                      1136
#define IDC_WRAP_V                      1137
#define IDC_SCREEN                      1140
#define IDC_NOTRANS                     1141
#define IDC_PRIORITY                    1143
#define IDC_CHECK9                      1163
#define IDC_CHECK10                     1164
#define IDC_CHECK11                     1165
#define IDC_CHECK12                     1166
#define IDC_CHECK13                     1167
#define IDC_CHECK14                     1168
#define IDC_CHECK15                     1169
#define IDC_CHECK16                     1170
#define IDC_CHECK26                     1171
#define IDC_CHECK27                     1172
#define IDC_CHECK28                     1173
#define IDC_CHECK29                     1174
#define IDC_CHECK30                     1175
#define IDC_CHECK31                     1176
#define IDC_CHECK32                     1177
#define IDC_CHECK33                     1178
#define IDC_COLOR                       1456
#define IDC_EDIT                        1490
#define IDC_SPIN                        1496
#define IDC_LENGTHEDIT                  3009
#define IDC_WIDTHEDIT                   3010
#define IDC_CREATECUBE                  3028
#define IDC_CREATEBOX                   3029
#define IDC_PRELIGHTVALUE               65535

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        123
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1150
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
